---
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
  database: beestore_development
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
  database: beestore_test
production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
