---
development:
  delivery_method: :letter_opener
  smtp_settings:
    address: email-smtp.us-east-1.amazonaws.com
    port: 587
    user_name:
    password:
    authentication: login
    enable_starttls_auto: true
  default_options:
    from: BeeStore <beestore@example.com>
  default_url_options:
    host: localhost:3000
    protocol:
test:
  delivery_method: :test
  smtp_settings:
    address: email-smtp.us-east-1.amazonaws.com
    port: 587
    user_name:
    password:
    authentication: login
    enable_starttls_auto: true
  default_options:
    from: BeeStore <beestore@example.com>
  default_url_options:
    host: localhost
    protocol:
production:
  delivery_method: :smtp
  smtp_settings:
    address: email-smtp.us-east-1.amazonaws.com
    port: 587
    user_name:
    password:
    authentication: login
    enable_starttls_auto: true
  default_options:
    from: BeeStore <beestore@example.com>
  default_url_options:
    host:
    protocol:
